# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.hello_pb2 as hello__pb2


class DemoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PrintHello = channel.unary_unary(
        '/Demo/PrintHello',
        request_serializer=hello__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__pb2.HelloReply.FromString,
        )


class DemoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PrintHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DemoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PrintHello': grpc.unary_unary_rpc_method_handler(
          servicer.PrintHello,
          request_deserializer=hello__pb2.HelloRequest.FromString,
          response_serializer=hello__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Demo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
